import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { Toaster } from "sonner";

const quicksand = Quicksand({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartStreak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`min-h-[100dvh] overflow-x-hidden bg-gradient-to-b from-background to-gray-900 ${quicksand.className}`}
        >
          <Toaster richColors />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
